title: AI-ML Conference & Journal Tracker
description: Ranked AI-ML conference deadlines and journal targets
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

url: "https://tirthajit.github.io"
baseurl: "/ai-ml-conference-journal-tracker"
